/**
 * Preset table dropdown rendering, filtering, and selection behavior.
 * Auto-extracted from the original scripts.js to improve maintainability.
 */

function wireDropdownEvents(){const dd=$("presetDropdown"),toggle=$("presetDropdownToggle"),menu=$("presetDropdownMenu");toggle.addEventListener("click",e=>{e.stopPropagation();dd.classList.toggle("open");});menu.addEventListener("click",e=>e.stopPropagation());document.addEventListener("click",()=>dd.classList.remove("open"));menu.addEventListener("change",e=>{if(e.target.classList.contains("presetCheckbox"))updateSelectedTablesFromUI();});$("presetSelectAll").addEventListener("click",()=>{document.querySelectorAll(".presetCheckbox:not(:disabled)").forEach(cb=>cb.checked=true);updateSelectedTablesFromUI();});$("presetClearAll").addEventListener("click",()=>{document.querySelectorAll(".presetCheckbox").forEach(cb=>cb.checked=false);updateSelectedTablesFromUI();});$("tableInput").addEventListener("input",updateSelectedTablesFromUI);$("tableSearch").addEventListener("input",function(){const term=this.value.toLowerCase().trim();document.querySelectorAll(".table-card").forEach(c=>c.style.display=c.innerText.toLowerCase().includes(term)?"":"none");});}

function renderPresetCheckboxesGrouped(){const list=$("presetCheckboxList");list.innerHTML="";presetGroups.forEach(g=>{const wrap=document.createElement("div");wrap.className="checkbox-group";const t=document.createElement("div");t.className="checkbox-group__title";t.textContent=g.name;wrap.appendChild(t);g.items.forEach(id=>{const label=document.createElement("label");label.className="table-card";label.dataset.tableId=id;label.setAttribute("for",`preset_${id}`);label.innerHTML=`<input type="checkbox" class="presetCheckbox" id="preset_${id}" value="${id}"><div class="table-card__content"><div class="table-card__title">${tableFriendlyNames[id]||id}</div><div class="table-card__id">${id}</div><div class="table-card__message"></div></div>`;wrap.appendChild(label);});list.appendChild(wrap);});}

function updateSelectedTablesFromUI(){const checked=Array.from(document.querySelectorAll(".presetCheckbox:checked")).map(cb=>cb.value);const custom=$("tableInput").value.trim()?$("tableInput").value.trim().split(/[\s,]+/):[];selectedTables=Array.from(new Set([...checked,...custom].filter(Boolean)));$("presetDropdownToggle").childNodes[0].nodeValue=checked.length?` ${checked.length} table${checked.length===1?"":"s"} selected `:" Select pre-set tables ";populateComparisonTopicOptions();}
